-- Resync identity sequences.
--
-- The explicit ids inserted above do not advance the GENERATED BY DEFAULT
-- AS IDENTITY sequences, so each sequence is pointed at its current maximum
-- to prevent collisions on future inserts. (Tables without rows keep the
-- sequence at its initial position.)

DO $$
DECLARE
  t regclass;
  seq_name text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'public.users',
    'public.offerings',
    'public.alerts',
    'public.allowed_file_types',
    'public.exercises',
    'public.exercises_attached_files',
    'public.exercises_compilation_files',
    'public.exercises_test_cases',
    'public.exercises_test_cases_files',
    'public.commits',
    'public.system_disk_reports',
    'public.system_logs',
    'public.mail_logs',
    'public.user_messages'
  ]::regclass[]
  LOOP
    seq_name := pg_get_serial_sequence(t::text, 'id');
    EXECUTE format(
      'SELECT setval(%L, COALESCE((SELECT max(id) FROM %s), 0), true)',
      seq_name,
      t::text
    );
  END LOOP;
END;
$$;
