SET ROLE TO runcodes;


CREATE TYPE user_t AS ENUM ('student', 'professor', 'admin', 'dev');

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  org_id text UNIQUE,
  password_hash text NOT NULL,
  role user_t DEFAULT 'student' NOT NULL,
  confirmed boolean DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE offerings (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  owner_id int REFERENCES users (id) ON DELETE CASCADE,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  visible_to_enroll boolean DEFAULT TRUE NOT NULL,
  enrollment_code text UNIQUE,
  description text,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TYPE alert_type_t AS ENUM ('info', 'warning', 'danger', 'success');
CREATE TYPE alert_recipients_t AS ENUM ( 'students', 'professors', 'monitors', 'all');

CREATE TABLE alerts (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type alert_type_t NOT NULL,
  recipients alert_recipients_t NOT NULL,
  offering_id int REFERENCES offerings (id) ON DELETE CASCADE,
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  read boolean DEFAULT FALSE NOT NULL
);

CREATE TYPE enrollment_role_t AS ENUM ('student', 'professor', 'monitor');

CREATE TABLE enrollments (
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  offering_id int REFERENCES offerings (id) ON DELETE CASCADE,
  role enrollment_role_t NOT NULL,
  banned boolean DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (user_id, offering_id)
);

CREATE TABLE allowed_file_types (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  extension text UNIQUE NOT NULL,
  is_compilable boolean DEFAULT TRUE NOT NULL,
  is_available boolean DEFAULT TRUE NOT NULL
);

CREATE TYPE exercise_type_t AS ENUM ('programming');

CREATE TABLE exercises (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offering_id int REFERENCES offerings (id) ON DELETE CASCADE,
  creator_id int REFERENCES users (id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  deadline TIMESTAMP WITH TIME ZONE NOT NULL,
  type exercise_type_t DEFAULT 'programming' NOT NULL,
  open_date TIMESTAMP WITH TIME ZONE NOT NULL,
  show_before_open_date boolean DEFAULT FALSE NOT NULL,
  removed boolean DEFAULT FALSE NOT NULL,
  ghost boolean DEFAULT FALSE NOT NULL,
  real_id int,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE exercises_attached_files (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  path text NOT NULL
);

CREATE TABLE exercises_compilation_files (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  path text NOT NULL
);

CREATE TABLE exercises_allowed_file_types (
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  allowed_file_type_id int REFERENCES allowed_file_types (id) ON DELETE CASCADE,
  PRIMARY KEY (exercise_id, allowed_file_type_id)
);

CREATE TYPE input_output_type_t AS ENUM ('text', 'file');

CREATE TABLE exercises_test_cases (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  input text NOT NULL,
  input_type input_output_type_t NOT NULL,
  show_input boolean DEFAULT TRUE NOT NULL,
  expected_output text NOT NULL,
  expected_output_type input_output_type_t NOT NULL,
  show_expected_output boolean DEFAULT TRUE NOT NULL,
  show_user_output boolean DEFAULT TRUE NOT NULL,
  cpu_time_limit_seconds int NOT NULL,
  mem_usage_limit_bytes int NOT NULL,
  stack_limit_bytes int NOT NULL,
  file_size_limit_bytes int NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE exercises_test_cases_files (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_test_case_id int REFERENCES exercises_test_cases (id) ON DELETE CASCADE,
  path text NOT NULL
);

CREATE TYPE commit_status_t AS ENUM ('pending', 'queued', 'compiling', 'compilation_error', 'running', 'completed', 'uncompleted', 'server_error', 'plagiarism', 'timeout');

CREATE TABLE commits (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  status commit_status_t DEFAULT 'pending' NOT NULL,
  num_correct_cases int DEFAULT 0 NOT NULL,
  score numeric(5, 2) DEFAULT 0 NOT NULL CHECK (score >= 0 AND score <= 100),
  compiled boolean,
  compilation_message text,
  compilation_started TIMESTAMP WITH TIME ZONE,
  compilation_finished TIMESTAMP WITH TIME ZONE,
  compilation_error text,
  ip inet,
  s3_key text
);

-- Ordered to match the legacy integer values (0 = killed_with_signal,
-- 1 = correct, 2 = bad_formatted_output) so ordinal-based comparisons keep
-- working consistently with the old data.
CREATE TYPE commit_exercise_test_case_status_t AS ENUM ('killed_with_signal', 'correct', 'bad_formatted_output');

CREATE TABLE commits_exercise_test_cases_results (
  commit_id int REFERENCES commits (id) ON DELETE CASCADE,
  exercise_test_case_id int REFERENCES exercises_test_cases (id) ON DELETE CASCADE,
  cpu_time numeric(15, 4) NOT NULL,
  mem_usage int NOT NULL,
  user_output text,
  user_output_type input_output_type_t NOT NULL,
  status commit_exercise_test_case_status_t NOT NULL,
  status_message text,
  error_message text,
  PRIMARY KEY (commit_id, exercise_test_case_id)
);

CREATE TABLE system_disk_reports (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disk_name text NOT NULL,
  total_space_kb bigint NOT NULL,
  used_space_kb bigint NOT NULL,
  free_space_kb bigint NOT NULL,
  report_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE system_logs (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  log_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  ip inet NOT NULL,
  action text NOT NULL
);

CREATE TABLE mail_logs (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sent_to text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  hash text NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE user_messages (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  recipes text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  attachments text,
  template text,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
