ALTER SCHEMA public OWNER TO runcodes;

SET ROLE TO runcodes;

CREATE TABLE exercises (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  description text,
  max_score numeric(5, 2) DEFAULT 100.0 NOT NULL CHECK (max_score >= 0 AND max_score <= 100.00),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE allowed_files (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  extension varchar(10) UNIQUE NOT NULL,
  is_compilable boolean DEFAULT TRUE NOT NULL,
  is_available boolean DEFAULT TRUE NOT NULL
);

CREATE TABLE exercises_allowed_files (
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  allowed_file_id int REFERENCES allowed_files (id) ON DELETE CASCADE,
  PRIMARY KEY (exercise_id, allowed_file_id)
);

CREATE TYPE user_t AS ENUM ('student', 'professor', 'admin');

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) UNIQUE NOT NULL,
  email varchar(100) UNIQUE NOT NULL,
  org_id varchar(50) UNIQUE,
  password_hash varchar(255) NOT NULL,
  type user_t DEFAULT 'student' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TYPE commit_status_t AS ENUM ('pending', 'queued', 'compiling', 'compilation_error', 'running', 'completed', 'timeout');

CREATE TABLE commits (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int REFERENCES users (id) ON DELETE CASCADE,
  exercise_id int REFERENCES exercises (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  status commit_status_t DEFAULT 'pending' NOT NULL,
  correct_test_cases int DEFAULT 0 NOT NULL,
  score numeric(5, 2) DEFAULT 0.0 NOT NULL CHECK (score >= 0 AND score <= 100.00),
  compiled boolean,
  compiled_message text,
  compilation_started TIMESTAMP WITH TIME ZONE,
  compilation_finished TIMESTAMP WITH TIME ZONE,
  compiled_error text,
  ip inet,
  s3_key varchar(150)
);

CREATE TABLE offerings (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  owner_id int REFERENCES users (id) ON DELETE CASCADE,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  enrollment_code varchar(4) UNIQUE NOT NULL,
  description text,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
