---
---  _____              _____          _
--- |  __ \            / ____|        | |
--- | |__) |   _ _ __ | |     ___   __| | ___  ___
--- |  _  / | | | '_ \| |    / _ \ / _` |/ _ \/ __|
--- | | \ \ |_| | | | | |___| (_) | (_| |  __/\__ \
--- |_|__\_\__,_|_| |_|\_____\___/ \__,_|\___||___/
--- |  __ \      | |      | |
--- | |  | | __ _| |_ __ _| |__   __ _ ___  ___
--- | |  | |/ _` | __/ _` | '_ \ / _` / __|/ _ \
--- | |__| | (_| | || (_| | |_) | (_| \__ \  __/
--- |_____/ \__,_|\__\__,_|_.__/ \__,_|___/\___|
---
--- I told them to just use Google Sheets for our database,
--- but no one ever listens to me.
--- -- Leug
---

--- I don't fell like typing all caps today.
set client_encoding = 'UTF8';

create user runcodes;

create database runcodes encoding 'UTF8' lc_collate 'C' lc_ctype 'C';

grant all privileges on database runcodes to runcodes;

alter schema public owner to runcodes;

---
--- Alerts Table
---

create type alert_t as enum (
    'system',
    'security',
    'user',
    'offering'
);

create type recipient_t as enum (
    'all_users',
    'admins',
    'professors'
);

create table alerts (
    id integer generated by default as identity primary key,
    alert_type alert_t not null,
    recipients recipient_t not null,
    offering_id integer references offerings (id) on delete set null,
    user_email varchar(100) not null,
    created_at timestampz default now() not null,
    expiration_date timestampz not null,
    is_sent boolean default false not null,
    sent_at timestamptz,
    title varchar(150) not null,
    message text not null,
    updated_at timestampz default now() not null
);

alter table alerts add constraint chk_valid_date
check (expiration_date >= created_at::timestampz);

--- add indexes for performance
create index idx_alerts_recipient_type on alerts (recipient_type);
create index idx_alerts_valid_until on alerts (valid_until);
create index idx_alerts_created_at on alerts (created_at);
create index idx_alerts_user_email on alerts (user_email);

revoke all on table alerts from public;
grant all on table alerts to runcodes;

alter table public.alerts owner to runcodes;

---
--- Allowed file types table
---

create table allowed_files (
    id integer generated by default as identity primary key,
    file_type varchar(100) unique not null,
    file_extension varchar(10) not null,
    compilable boolean default true not null,
    available boolean default true not null
);

revoke all on table allowed_files from public;
grant all on table allowed_files to runcodes;

alter table public.allowed_files owner to runcodes;

create table allowed_files_exercises (
    exercise_id integer references exercises (id) on delete cascade,
    allowed_file_id integer references allowed_files (id) on delete cascade,
    primary key (exercise_id, allowed_file_id)
);

alter table public.allowed_files_exercises owner to runcodes;

---
--- Commits Table
---

create type commit_status_t as enum (
    'pending',
    'compiling',
    'compilation_error',
    'running',
    'completed',
    'timeout'
);

create table commits (
    id integer generated by default as identity primary key,
    user_email varchar(100) not null,
    exercise_id integer references exercises (id) on delete cascade,
    commit_time timestampz default now() not null,
    status commit_status_t default 'pending' not null,
    correct_test_cases integer default 0,
    score numeric(10, 2) default 0.0,
    compiled boolean default false,
    compiled_message text,
    compilation_started timestampz,
    compilation_finished timestampz,
    compiled_error text default ''::text,
    ip varchar(30) default null::varchar,
    s3_key varchar(150) default null::varchar
);

alter table public.commits owner to runcodes;


---
--- exercises
---

create table exercises (
    id integer generated by default as identity primary key,
    exercise_name varchar(100) not null,
    description text,
    max_score numeric(10, 2) default 100.0,
    created_at timestampz default now() not null,
    updated_at timestampz default now() not null
);


create table offerings (
    id serial primary key,
    offering_name varchar(255) not null,
    description text,
    created_at timestampz default now() not null,
    updated_at timestampz default now() not null
);

create table users (
    id integer generated by default as identity primary key,
    user_name varchar(100) unique not null,
    user_email varchar(100) unique not null,
    -- organization-specific user id, e.g., university id. can be used to login.
    user_org_id varchar(50) unique not null,
    password_hash varchar(255) not null,
    created_at timestampz default now() not null,
    updated_at timestampz default now() not null
);
